add_library(
    Game
    Boundary.cpp
    Controller.cpp
    CollisionEngine.cpp
    Match.cpp
    GameScreen.cpp
    HomeScreen.cpp
    BoundaryCircle.cpp
    BoundaryLine.cpp
    LocalPlayerGameEventWindow.cpp
    LineXZ.cpp
)

target_link_libraries(Game
    glfw
    glm
    Renderer
    UI
    connection
)